- name: Инициализация первого control-plane
  ansible.builtin.command: |
    kubeadm init --apiserver-advertise-address {{ ansible_host }}
    --pod-network-cidr 10.244.0.0/16 --upload-certs --control-plane-endpoint {{ control_plane_endpoint }}
  register: kubeadm_output
  changed_when: false
  failed_when: kubeadm_output.rc > 0
  when: "(groups['masters'] | first) == inventory_hostname"

- name: Сохраняем команду для ввода в кластер как факт
  ansible.builtin.set_fact:
    kubejoin_command: "{{ kubeadm_output.stdout | regex_search('^kubeadm join .*\n.*', multiline=True) | regex_replace('\\\n\t', '') }}"
    kubejoincontrol_command: "{{ kubeadm_output.stdout | regex_search('^  kubeadm join .*\n.*\n.*', multiline=True) | regex_replace('\\\n\t', '') }}"
  delegate_to: localhost
  run_once: true
  # when: "(groups['masters'] | first) == inventory_hostname"

- name: Test
  ansible.builtin.debug:
    msg: |
      "{{ hostvars[inventory_hostname]['kubejoin_command'] }}"
      "{{ hostvars[inventory_hostname]['kubejoincontrol_command'] }}"
  run_once: true

- name: Вводим остальные masters в кластер
  ansible.builtin.command: "{{ hostvars[inventory_hostname]['kubejoincontrol_command'] }}"
  register: kubeadm_output
  changed_when: false
  failed_when: kubeadm_output.rc > 0
  when: "('masters' in group_names) and ((groups['masters'] | first) != inventory_hostname)"

- name: Вводим workers в кластер
  ansible.builtin.command: "{{ hostvars[inventory_hostname]['kubejoin_command'] }}"
  register: kubeadm_output
  changed_when: false
  failed_when: kubeadm_output.rc > 0
  when: "'workers' in group_names"

- name: Создаём директорию ~/.kube
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0700'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  when: "(groups['masters'] | first) == inventory_hostname"

- name: Копируем конфиг kubectl
  ansible.builtin.copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: '{{ ansible_user }}'
  when: "(groups['masters'] | first) == inventory_hostname"

- name: Устанавливаем cni flannel
  block:
    - name: Скачиваем манифест аддона cni flannel
      ansible.builtin.get_url:
        url: https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
        dest: /tmp/kube-flannel.yml
        mode: '0664'
      become: false
      delegate_to: localhost
      run_once: true

    - name: Копируем на хосты манифест аддона cni flannel
      ansible.builtin.copy:
        src: /tmp/kube-flannel.yml
        dest: /tmp/kube-flannel.yml
        mode: '0664'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      when: "(groups['masters'] | first) == inventory_hostname"

    - name: Применяем манифест cni flannel
      ansible.builtin.command: kubectl apply -f /tmp/kube-flannel.yml
      become: false
      register: kubectl_output
      changed_when: false
      failed_when: kubectl_output.rc > 0
      when: "(groups['masters'] | first) == inventory_hostname"
